### ISSUE TITLE
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  方式不行

### ISSUE THREAD

**Issue by mejinke** [qiniu/iconv#10]
sh-3.2# CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build autohome.go 
github.com/qiniu/iconv
../../github.com/qiniu/iconv/reader.go:10: undefined: Iconv
../../github.com/qiniu/iconv/reader.go:17: undefined: Iconv
../../github.com/qiniu/iconv/reader.go:18: undefined: DefaultBufSize
../../github.com/qiniu/iconv/reader.go:42: undefined: EILSEQ
../../github.com/qiniu/iconv/writer.go:11: undefined: Iconv
../../github.com/qiniu/iconv/writer.go:17: undefined: Iconv
../../github.com/qiniu/iconv/writer.go:18: undefined: DefaultBufSize
../../github.com/qiniu/iconv/writer.go:63: undefined: EILSEQ
../../github.com/qiniu/iconv/writer.go:89: undefined: EILSEQ

**Comment by Wang-Kai** [comment]
我在 mac 上 使用 

> GOOS=linux CGO_ENABLED=1 GOARCH=amd64 go build -i -o build

也不行 ./gopkg.in/iconv.v1/reader.go:10: undefined: Iconv
