### ISSUE TITLE
在windows底下get时报iconv.h: No such file or directory错误

### ISSUE THREAD

**Issue by xlqstar** [qiniu/iconv#11]
我是windows8，在执行go get github.com/qiniu/iconv时报如下错误

github.com/qiniu/iconv
iconv.go:6:20: fatal error: iconv.h: No such file or directory
compilation terminated.

群里有朋友说是因为系统问题，linux底下就好了，特此问下有没有windows底下的解决办法？

**Comment by fm123456** [comment]
怎么解决这个要

**Comment by truth** [comment]
@fm123456 请使用golang.org/x/text/encoding替代iconv
