### ISSUE TITLE
编译时报 gcc: 错误：unrecognized command line option ‘-mthreads’ 错误

### ISSUE THREAD

**Issue by haochun** [qiniu/iconv#21]
编译命令是  CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o bin/xxxx.exe client
如果 CGO_ENABLED=0 就报错src/common/iconv/reader.go:10: undefined: Iconv
求教这个是哪里有问题？

**Comment by haochun** [comment]
我只要调用 go get github.com/qiniu/iconv。如果GOOS设置为windows就会出这个错误，换成linux就没问题。。

**Comment by xushiwei** [comment]
cgo 不支持交叉编译
