### ISSUE TITLE
Problem with MingW

### ISSUE THREAD

**Issue by ComSecNinja** [qiniu/iconv#29]
Go-getting the package results in the following error:

	[path-to-mingw-lib]../lib/libiconv.a(localcharset.o):localcharset.c (.text+0x8): undefined reference to `__imp_GetACP'
	collect2.exe: error: ld returned 1 exit status

MingW version 5.2.0, Windows 64-bit build, Win10

**Comment by crazybytes** [comment]
you need libzbar.a
