### ISSUE TITLE
Can't work with golang 1.6.x

### ISSUE THREAD

**Issue by drmfly** [qiniu/iconv#31]
runtime error: cgo argument has Go pointer to Go pointer

**Comment by drmfly** [comment]
work with GODEBUG=cgocheck=0

**Comment by awalterschulze** [comment]
My team mate just fixed our iconv library.
Maybe this clue will help you.
He added this to the top of the file.

```
//#include <iconv.h>
//#include <errno.h>
//#include <stdio.h>
//#include <stdlib.h>
//
// size_t iconv_bridge(iconv_t t, char *in, size_t *in_size, char *out, size_t *out_size) {
//                           return iconv(t, &in, in_size, &out, out_size);
// }
//
```

And used this function rather than directly using the iconv function.
