### ISSUE TITLE
../gopkg.in/iconv.v1/reader.go:10:5: undefined: Iconv

### ISSUE THREAD

**Issue by Barbery** [qiniu/iconv#46]
go run是可以的，go build或者go install 就报这个错误`../gopkg.in/iconv.v1/reader.go:10:5: undefined: Iconv`

**Comment by chenzi** [comment]
我也报这个错误！

**Comment by Barbery** [comment]
没必要用这个库了，用transform原生库就可以了

**Comment by Wang-Kai** [comment]
macOS Mojave 10.14.5 环境下，示例代码中 `GOOS=linux go build .` 都会报错：

```
GOOS=linux go build .
# gopkg.in/iconv.v1
../../reader.go:10:5: undefined: Iconv
```

这个项目估计已经不可用了
